# Import Libraries

In [ ]:
import numpy as np
import pandas as pd

https://drive.google.com/file/d/11bXsk8hiDlU9_9j1BKcnPE3U8OdDcKsA/view?usp=share_link

# Download the dataset

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/Applied Data Science/Datasets and Notebooks/Datasets/50_Startups.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

# Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])

In [ ]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [ ]:
x  = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [ ]:
x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [ ]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ],


# One-Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)


In [ ]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

# Train,Test & Split

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [ ]:
x_train.shape

(86, 6)

# Model Building

# Importing Libraries

> Indented block



In [ ]:
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [ ]:
import tensorflow as tf


In [ ]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [ ]:

x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [ ]:
5 * x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [ ]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
tf.concat([x, x, x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [ ]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


In [ ]:
var = tf.Variable([0.0, 0.0, 0.0])

In [ ]:
var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [ ]:
var.assign([1, 2, 3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

In [ ]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Create 3 layers
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

In [ ]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
model.layers

In [ ]:
layer = layers.Dense(3)
layer.weights  # Empty

[]

In [ ]:
# Call layer on a test input
x = tf.ones((1, 4))
y = layer(x)
layer.weights  # Now it has weights, of shape (4, 3) and (3,)

[<tf.Variable 'dense/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[-0.19817936, -0.6249985 ,  0.7547616 ],
        [ 0.6318432 ,  0.22759569, -0.15264195],
        [ 0.05555379,  0.23493242,  0.45267558],
        [-0.02618682,  0.7304938 ,  0.5674261 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


You can also create a Sequential model incrementally via the add() method:



In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(layers.Dense(2, activation="relu"))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


# Initialize the Model

In [ ]:
regressor = Sequential()

In [ ]:
x_train.shape

(86, 6)

# Add Layers

In [ ]:
regressor.add(Dense(units = 4,kernel_initializer  = 'random_uniform',activation = 'relu'))

In [ ]:
regressor.add(Dense(units = 12,kernel_initializer = 'random_uniform',activation = 'relu')) # 1st hidden layer

In [ ]:
regressor.add(Dense(units = 8,kernel_initializer = 'random_uniform',activation = 'relu')) # second hiden layer

In [ ]:
regressor.add(Dense(units = 9,kernel_initializer = 'random_uniform',activation = 'relu')) # third Hidden layer

# Output Layer

In [ ]:
regressor.add(Dense(units = 1,kernel_initializer = 'random_uniform'))

# Compile The Model

In [ ]:
regressor.compile(optimizer = 'adam',loss = 'mse',metrics = ['mse'])

# Fit The Model

In [ ]:
regressor.fit(x_train,y_train , batch_size = 10,epochs = 300)

Epoch 1/300
9/9 [==============================] - 4s 11ms/step - loss: 14435131392.0000 - mse: 14435131392.0000
Epoch 2/300
9/9 [==============================] - 0s 6ms/step - loss: 14435086336.0000 - mse: 14435086336.0000
Epoch 3/300
9/9 [==============================] - 0s 5ms/step - loss: 14434930688.0000 - mse: 14434930688.0000
Epoch 4/300
9/9 [==============================] - 0s 5ms/step - loss: 14434425856.0000 - mse: 14434425856.0000
Epoch 5/300
9/9 [==============================] - 0s 5ms/step - loss: 14433049600.0000 - mse: 14433049600.0000
Epoch 6/300
9/9 [==============================] - 0s 5ms/step - loss: 14428782592.0000 - mse: 14428782592.0000
Epoch 7/300
9/9 [==============================] - 0s 7ms/step - loss: 14417227776.0000 - mse: 14417227776.0000
Epoch 8/300
9/9 [==============================] - 0s 5ms/step - loss: 14389609472.0000 - mse: 14389609472.0000
Epoch 9/300
9/9 [==============================] - 0s 9ms/step - loss: 14323750912.0000 - mse: 14323750

# Test The Model

In [ ]:
y_pred = regressor.predict(x_test)

1/1 [==============================] - 0s 166ms/step


In [ ]:
y_pred

array([[ 43836.062],
       [127282.92 ],
       [ 80776.45 ],
       [175703.73 ],
       [ 98388.35 ],
       [122098.055],
       [127828.68 ],
       [167026.14 ],
       [118171.164],
       [ 46988.95 ],
       [105503.74 ],
       [119532.46 ],
       [ 43836.062],
       [132522.11 ],
       [ 65432.305],
       [131140.   ],
       [131140.   ],
       [103906.82 ],
       [ 67632.375],
       [142878.06 ],
       [157382.06 ],
       [160362.   ]], dtype=float32)

In [ ]:
y_test

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77]])

# Calculate R2_Score

In [ ]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [ ]:
accuracy

0.8310800083370152

model.save('regressor.h5')

# Save the Model

In [ ]:
regressor.save('regressor.h5')

#reg  = model.load("/regressor.h5")

In [ ]:
x_train.shape

(86, 6)

In [ ]:
regressor.predict(np.array([[0,1,0,50000,60000,70000]]))

1/1 [==============================] - 0s 152ms/step


array([[60370.64]], dtype=float32)